name: 'AI-Powered PR Description Generator'
description: 'Utilizes advanced AI algorithms to automatically generate pull request descriptions.'
author: 'Rock Chen'
runs:
  using: 'node20'
  main: './dist/bundle.js'
inputs:
  ai_name:
    description: 'The name of AI, currently just supports gemini, open-ai'
    required: true
    default: 'gemini'
  ai_model:
    description: 'Model to use. Default depends on ai_name: gemini -> gemini-1.5-pro, open-ai -> gpt-4.1.'
    required: false
  api_key:
    description: 'API key for the selected provider (Gemini/OpenAI). Ensure it has the necessary permissions for generating content.'
    required: true
  github_token:
    description: 'GitHub token with repository permissions to access and modify pull requests. Make sure it has at least read and write access to pull requests.'
    required: true
  temperature:
    description: 'Controls the randomness of the generated descriptions. A value between 0.0 (more deterministic) and 1.0 (more creative).'
    required: false
    default: '0.7'
  ignores:
    description: 'AI will not analyze changes to files or folders in this array'
    required: false
  use_jira:
    description: 'Add Jira ticket by checking branch name'
    required: false
    default: 'false'
  update_title:
    description: 'Whether to also update the PR title using AI.'
    required: false
    default: 'false'
outputs:
  description:
    description: 'The AI-generated description for the pull request, providing context and details for reviewers.'
branding:
  icon: 'AI-Powered PR'
  color: 'red'
