name: 'AI-Powered PR Description Generator'
description: 'Utilizes advanced AI algorithms to automatically generate pull request descriptions.'
author: 'Rock Chen'
runs:
  using: 'node20'
  main: './dist/bundle.js'
inputs:
  ai_name:
    description: 'The name of AI, currently just supports gemini, open-ai'
    required: true
    default: 'gemini'
  gemini_model:
    description: 'Gemini model to use (e.g., gemini-1.5-pro, gemini-1.5-flash, gemini-1.5-flash-8b). Defaults to gemini-1.5-pro.'
    required: false
    default: 'gemini-1.5-pro'
  openai_model:
    description: 'OpenAI model to use (e.g., gpt-4.1, gpt-4.1-mini). Defaults to gpt-4.1.'
    required: false
    default: 'gpt-4.1'
  api_key:
    description: 'API key for authenticating with Google Gemini service. Ensure it has the necessary permissions for generating content.'
    required: true
  github_token:
    description: 'GitHub token with repository permissions to access and modify pull requests. Make sure it has at least read and write access to pull requests.'
    required: true
  temperature:
    description: 'Controls the randomness of the generated descriptions. A value between 0.0 (more deterministic) and 1.0 (more creative).'
    required: false
    default: '0.7'
  ignores:
    description: 'AI will not analyze changes to files or folders in this array'
    required: false
  use_jira:
    description: 'Add Jira ticket by checking branch name'
    required: false
    default: 'false'
outputs:
  description:
    description: 'The AI-generated description for the pull request, providing context and details for reviewers.'
branding:
  icon: 'AI-Powered PR'
  color: 'red'
