export const GITMOJI_LEGEND: Record<string, string> = {
  '🎨': 'Improve structure/format of the code',
  '⚡️': 'Improve performance',
  '🔥': 'Remove code or files',
  '🐛': 'Fix a bug',
  '🚑️': 'Critical hotfix',
  '✨': 'Introduce new features',
  '📝': 'Add/update documentation',
  '🚀': 'Deploy',
  '💄': 'Update UI/style files',
  '🎉': 'Begin a project',
  '✅': 'Add/update/pass tests',
  '🔒️': 'Fix security/privacy issues',
  '🔐': 'Add/update secrets',
  '🔖': 'Release / tags',
  '🚨': 'Fix compiler/linter warnings',
  '🚧': 'Work in progress',
  '💚': 'Fix CI build',
  '⬇️': 'Downgrade dependencies',
  '⬆️': 'Upgrade dependencies',
  '📌': 'Pin dependencies',
  '👷': 'CI build system',
  '📈': 'Analytics/telemetry',
  '♻️': 'Refactor code',
  '➕': 'Add a dependency',
  '➖': 'Remove a dependency',
  '🔧': 'Config files',
  '🔨': 'Dev scripts',
  '🌐': 'i18n/l10n',
  '✏️': 'Fix typos',
  '⏪️': 'Revert changes',
  '🔀': 'Merge branches',
  '📦️': 'Compiled files/packages',
  '👽️': 'External API changes',
  '🚚': 'Move/rename resources',
  '📄': 'License',
  '💥': 'Breaking changes',
  '🍱': 'Assets',
  '♿️': 'Accessibility',
  '💡': 'Comments',
  '💬': 'Text/literals',
  '🗃️': 'Database changes',
  '🔊': 'Add/update logs',
  '🔇': 'Remove logs',
  '👥': 'Contributors',
  '🚸': 'UX/usability',
  '📱': 'Responsive design',
  '🤡': 'Mocks',
  '🙈': '.gitignore',
  '📸': 'Snapshots',
  '⚗️': 'Experiments',
  '🔍️': 'SEO',
  '🏷️': 'Types',
  '🌱': 'Seeds',
  '🚩': 'Feature flags',
  '🥅': 'Catch errors',
  '💫': 'Animations/transitions',
  '🛂': 'Auth/permissions',
  '🩹': 'Simple non-critical fix',
  '🧐': 'Data exploration',
  '⚰️': 'Remove dead code',
  '🧪': 'Failing test',
  '👔': 'Business logic',
  '🩺': 'Healthcheck',
  '🧱': 'Infrastructure',
  '🧑‍💻': 'Developer experience',
  '💸': 'Sponsorships/money infra',
  '🧵': 'Concurrency',
  '🦺': 'Validation',
  '✈️': 'Offline support'
};

